#!/usr/bin/env python3
"""
Migrate one epic from docs/requirements.yaml to the nested tree under
docs/requirements/. Idempotent: re-running on the same epic regenerates
the same files byte-for-byte (modulo the `updated:` field, which is held
constant at the migration date defined in the brief).

Usage:
    python tools/req/migrate_epic.py EPIC-008
    python tools/req/migrate_epic.py --all          # migrates every epic
    python tools/req/migrate_epic.py --dry-run EPIC-008

The script is the helper called for both pass 1 (EPIC-008 only) and pass 2
(every other epic). Decisions encoded here are the ones locked in the brief:
- ID mapping: EPIC-NNN → gw_epic_<NNN>, FEAT-NNN → gw_feature_<NNN>, STORY-NNN → gw_story_<NNN>
- Slug: kebab-cased title, ≤60 chars
- Status: every discipline = not_started uniformly
- Created/updated: 2026-05-07 (the migration date)
- Priority mapping: P0→mvp, P1→v1.1, P2→v2.0, P3→backlog
- Order: trailing integer of the original ID
- Inherits non_functional_baseline + ui_baseline implicitly (omitted from frontmatter)
- Self-edges in depends_on are dropped (recorded in the migration report)
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
LEGACY_PATH = REPO_ROOT / "docs" / "requirements.yaml"
REQ_ROOT = REPO_ROOT / "docs" / "requirements"
MIGRATION_DATE = "2026-05-07"

PRIORITY_TO_RELEASE = {"P0": "mvp", "P1": "v1.1", "P2": "v2.0", "P3": "backlog"}

OLD_ID_RE = re.compile(r"^(EPIC|FEAT|STORY)-(\d{1,5})$")


def slugify(title: str, max_len: int = 60) -> str:
    s = title.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    if len(s) > max_len:
        s = s[:max_len].rstrip("-")
    return s or "untitled"


def map_id(old: str) -> str:
    m = OLD_ID_RE.match(old)
    if not m:
        raise ValueError(f"unrecognised legacy id: {old}")
    kind = {"EPIC": "epic", "FEAT": "feature", "STORY": "story"}[m.group(1)]
    return f"gw_{kind}_{int(m.group(2)):05d}"


def map_id_list(values: Optional[List[str]]) -> List[str]:
    if not values:
        return []
    return [map_id(v) for v in values]


def order_from_old_id(old: str) -> int:
    m = OLD_ID_RE.match(old)
    if not m:
        return 0
    return int(m.group(2))


def initial_status_block() -> Dict[str, str]:
    return {d: "not_started" for d in ("backend", "frontend", "infra", "docs", "qa")}


def yaml_dump(data: Dict[str, Any]) -> str:
    return yaml.safe_dump(
        data, sort_keys=False, allow_unicode=True, default_flow_style=False, width=2_000_000
    )


def write_node(path: Path, frontmatter: Dict[str, Any], body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fm_text = yaml_dump(frontmatter)
    if not body.endswith("\n"):
        body = body + "\n"
    path.write_text(f"---\n{fm_text}---\n{body}", encoding="utf-8")


# ---------------------------------------------------------------------------
# Body builders
# ---------------------------------------------------------------------------

GENERATED_BLOCK_START = "<!-- generated:children:start -->"
GENERATED_BLOCK_END = "<!-- generated:children:end -->"


def build_epic_body(epic: Dict[str, Any]) -> str:
    title = epic["title"]
    description = epic.get("description", "").strip() or "_(no description in source YAML)_"
    return (
        f"# {title}\n\n"
        f"## Summary\n\n{description}\n\n"
        f"## Features\n\n{GENERATED_BLOCK_START}\n_(regenerated by `req index`)_\n{GENERATED_BLOCK_END}\n\n"
        f"## Notes\n\n_None._\n"
    )


def build_feature_body(
    feature: Dict[str, Any],
    external_refs: Optional[Dict[str, List[str]]] = None,
    dropped_self_edges: Optional[List[str]] = None,
) -> str:
    title = feature["title"]
    description = feature.get("description", "").strip() or "_(no description in source YAML)_"
    extra_notes: List[str] = []
    for k in ("mode",):
        if feature.get(k):
            extra_notes.append(f"- **{k}** (from source YAML): `{feature[k]}`")
    if dropped_self_edges:
        extra_notes.append(
            "- **Migration note:** dropped self-edge in `depends_on` "
            f"(`{', '.join(dropped_self_edges)}`); flagged for manual review."
        )
    if external_refs:
        extra_notes.append(_format_external_block(
            "External cross-epic references (will move to frontmatter once their epic is migrated in pass 2)",
            external_refs,
        ))
    notes = "\n".join(extra_notes) if extra_notes else "_None._"
    return (
        f"# {title}\n\n"
        f"## Summary\n\n{description}\n\n"
        f"## Stories\n\n{GENERATED_BLOCK_START}\n_(regenerated by `req index`)_\n{GENERATED_BLOCK_END}\n\n"
        f"## Notes\n\n{notes}\n"
    )


def render_bullets(items: Optional[List[Any]]) -> str:
    if not items:
        return "_None._"
    out = []
    for it in items:
        if isinstance(it, str):
            out.append(f"- {it}")
        elif isinstance(it, dict):
            # Render generic dicts as inline yaml under a bullet
            out.append("- " + yaml_dump(it).strip().replace("\n", "\n  "))
        else:
            out.append(f"- {it}")
    return "\n".join(out)


def render_api(api: Optional[List[Any]]) -> str:
    if not api:
        return "_None._"
    out: List[str] = []
    for entry in api:
        if not isinstance(entry, dict):
            out.append(f"- {entry}")
            continue
        method = entry.get("method", "")
        path = entry.get("path", "")
        head = f"### `{method} {path}`".strip()
        if head == "### ``":
            head = "### (unspecified endpoint)"
        out.append(head)
        notes = entry.get("notes")
        if notes:
            out.append(notes)
        for sub in ("request", "response", "errors"):
            sv = entry.get(sub)
            if sv is None:
                continue
            out.append(f"**{sub.capitalize()}:**")
            out.append("")
            out.append("```yaml")
            out.append(yaml_dump({sub: sv}).rstrip())
            out.append("```")
        if entry.get("inferred"):
            out.append("_inferred: true (carried over from source YAML)_")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_ui(ui: Optional[Dict[str, Any]]) -> str:
    if not ui:
        return "_None._"
    if not isinstance(ui, dict):
        return f"```yaml\n{yaml_dump({'ui': ui}).rstrip()}\n```"
    parts: List[str] = []
    for label, key in [("Screens", "screens"), ("Components", "components"), ("States", "states")]:
        v = ui.get(key)
        if v:
            parts.append(f"**{label}:**\n")
            parts.append(render_bullets(v))
            parts.append("")
    extra = {k: v for k, v in ui.items() if k not in ("screens", "components", "states")}
    if extra:
        parts.append("**Other UI metadata (preserved from source YAML):**\n")
        parts.append("```yaml")
        parts.append(yaml_dump(extra).rstrip())
        parts.append("```")
    return "\n".join(parts).rstrip() + "\n" if parts else "_None._"


def build_acceptance_section(acs: Optional[List[Any]]) -> str:
    if not acs:
        return "_None defined in source YAML._"
    out: List[str] = []
    for ac in acs:
        if not isinstance(ac, dict):
            continue
        ac_id = ac.get("id", "AC-???")
        scenario = ac.get("scenario", "(no scenario)")
        out.append(f"### {ac_id} — {scenario}")
        out.append("")
        for label, key in [("Given", "given"), ("When", "when"), ("Then", "then")]:
            vals = ac.get(key) or []
            out.append(f"**{label}:**")
            out.append("")
            for v in vals:
                out.append(f"- {v}")
            if not vals:
                out.append("- _(none specified)_")
            out.append("")
        # Capture any extra ac fields verbatim (e.g. notes)
        extra = {k: v for k, v in ac.items() if k not in ("id", "scenario", "given", "when", "then")}
        if extra:
            out.append("```yaml")
            out.append(yaml_dump(extra).rstrip())
            out.append("```")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def _format_external_block(label: str, external_refs: Dict[str, List[str]]) -> str:
    if not external_refs:
        return ""
    lines = [f"\n**{label}:**\n"]
    for key in sorted(external_refs):
        vals = sorted(set(external_refs[key]))
        lines.append(f"- `{key}`: {', '.join(f'`{v}`' for v in vals)}")
    return "\n".join(lines)


def build_story_body(
    story: Dict[str, Any],
    dropped_self_edges: List[str],
    external_refs: Optional[Dict[str, List[str]]] = None,
) -> str:
    title = story["title"]
    nar = story.get("narrative") or {}
    as_a = nar.get("as_a", "")
    iw = nar.get("i_want", "")
    st = nar.get("so_that", "")
    narrative_line = f"As a {as_a}, I want {iw} so that {st}."
    ac_block = build_acceptance_section(story.get("acceptance_criteria"))
    api_block = render_api(story.get("api"))
    ui_block = render_ui(story.get("ui"))
    dm_block = render_bullets(story.get("data_models"))
    nf_block = render_bullets(story.get("non_functional"))
    notes_lines: List[str] = []
    if story.get("audiences"):
        notes_lines.append("**Audiences (from source YAML):** " + ", ".join(story["audiences"]))
    if story.get("notes"):
        if isinstance(story["notes"], list):
            for n in story["notes"]:
                notes_lines.append(f"- {n}")
        else:
            notes_lines.append(str(story["notes"]))
    # Preserve any extra unmapped keys verbatim
    known = {"id", "feature", "title", "narrative", "priority", "acceptance_criteria",
             "api", "ui", "data_models", "non_functional", "depends_on", "related",
             "supersedes", "superseded_by", "audiences", "also_under", "lifecycle", "notes"}
    extras = {k: v for k, v in story.items() if k not in known}
    if extras:
        notes_lines.append("\n**Additional metadata preserved from source YAML:**\n")
        notes_lines.append("```yaml")
        notes_lines.append(yaml_dump(extras).rstrip())
        notes_lines.append("```")
    if dropped_self_edges:
        notes_lines.append("\n**Migration note:** the source YAML had a self-edge in `depends_on` "
                           "(`" + ", ".join(dropped_self_edges) + "`). It was dropped during migration "
                           "to preserve DAG validity; flagged for manual review.")
    if external_refs:
        notes_lines.append(_format_external_block(
            "External cross-epic references (will move to frontmatter once their epic is migrated in pass 2)",
            external_refs,
        ))
    notes_block = "\n".join(notes_lines).strip() or "_None._"
    return (
        f"# {title}\n\n"
        f"## Narrative\n\n{narrative_line}\n\n"
        f"## Acceptance Criteria\n\n{ac_block}\n"
        f"## API\n\n{api_block}\n"
        f"## UI\n\n{ui_block}\n"
        f"## Data Models\n\n{dm_block}\n\n"
        f"## Non-Functional Requirements\n\n{nf_block}\n\n"
        f"## Notes\n\n{notes_block}\n\n"
        f"## Open Questions\n\n_None._\n"
    )


# ---------------------------------------------------------------------------
# Frontmatter builders
# ---------------------------------------------------------------------------

def epic_frontmatter(epic: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "id": map_id(epic["id"]),
        "type": "epic",
        "title": epic["title"],
        "lifecycle": epic.get("lifecycle", "active"),
        "created": MIGRATION_DATE,
        "updated": MIGRATION_DATE,
        "release": PRIORITY_TO_RELEASE.get(epic.get("priority"), "backlog"),
        "order": order_from_old_id(epic["id"]),
        "owners": [],
        "tags": [],
    }


def _split_internal_external(
    refs: Optional[List[str]],
    in_scope: set,
) -> Tuple[List[str], List[str]]:
    """Return (internal, external) — refs that resolve in-scope vs those that
    point outside the migration set (will reconnect in pass 2)."""
    if not refs:
        return [], []
    internal: List[str] = []
    external: List[str] = []
    for r in refs:
        if r in in_scope:
            internal.append(r)
        else:
            external.append(r)
    return internal, external


def feature_frontmatter(
    feature: Dict[str, Any],
    dropped_self_edges: List[str],
    in_scope: set,
    external_refs: Dict[str, List[str]],
) -> Dict[str, Any]:
    fm: Dict[str, Any] = {
        "id": map_id(feature["id"]),
        "type": "feature",
        "title": feature["title"],
        "lifecycle": feature.get("lifecycle", "active"),
        "created": MIGRATION_DATE,
        "updated": MIGRATION_DATE,
        "parent": map_id(feature["epic"]),
        "release": PRIORITY_TO_RELEASE.get(feature.get("priority"), "backlog"),
        "order": order_from_old_id(feature["id"]),
        "status": initial_status_block(),
        "deployment_modes": ["saas", "self_hosted"],
        "installed_on": "tenant_install",
        "owners": [],
        "tags": [],
    }
    deps_new: List[str] = []
    for d in feature.get("depends_on") or []:
        if d == feature["id"]:
            dropped_self_edges.append(feature["id"])
            continue
        deps_new.append(map_id(d))
    internal, external = _split_internal_external(deps_new, in_scope)
    if internal:
        fm["depends_on"] = internal
    if external:
        external_refs.setdefault("depends_on", []).extend(external)
    for key in ("related", "supersedes"):
        v = feature.get(key)
        if v:
            ints, exts = _split_internal_external([map_id(x) for x in v], in_scope)
            if ints:
                fm[key] = ints
            if exts:
                external_refs.setdefault(key, []).extend(exts)
    if feature.get("superseded_by"):
        sb = map_id(feature["superseded_by"])
        if sb in in_scope:
            fm["superseded_by"] = sb
        else:
            external_refs.setdefault("superseded_by", []).append(sb)
    if feature.get("also_under"):
        ints, exts = _split_internal_external(map_id_list(feature["also_under"]), in_scope)
        if ints:
            fm["also_under"] = ints
        if exts:
            external_refs.setdefault("also_under", []).extend(exts)
    if feature.get("ui_references"):
        fm["ui_references"] = list(feature["ui_references"])
    if feature.get("external"):
        fm["external"] = feature["external"]
    return fm


def story_frontmatter(
    story: Dict[str, Any],
    dropped_self_edges: List[str],
    in_scope: set,
    external_refs: Dict[str, List[str]],
) -> Dict[str, Any]:
    fm: Dict[str, Any] = {
        "id": map_id(story["id"]),
        "type": "story",
        "title": story["title"],
        "lifecycle": story.get("lifecycle", "active"),
        "created": MIGRATION_DATE,
        "updated": MIGRATION_DATE,
        "parent": map_id(story["feature"]),
        "release": PRIORITY_TO_RELEASE.get(story.get("priority"), "backlog"),
        "order": order_from_old_id(story["id"]),
        "status": initial_status_block(),
        "narrative": {
            "as_a": (story.get("narrative") or {}).get("as_a", ""),
            "i_want": (story.get("narrative") or {}).get("i_want", ""),
            "so_that": (story.get("narrative") or {}).get("so_that", ""),
        },
        "owners": [],
        "tags": [],
    }
    deps_new: List[str] = []
    for d in story.get("depends_on") or []:
        if d == story["id"]:
            dropped_self_edges.append(story["id"])
            continue
        deps_new.append(map_id(d))
    internal, external = _split_internal_external(deps_new, in_scope)
    if internal:
        fm["depends_on"] = internal
    if external:
        external_refs.setdefault("depends_on", []).extend(external)
    for key in ("related", "supersedes"):
        v = story.get(key)
        if v:
            ints, exts = _split_internal_external([map_id(x) for x in v], in_scope)
            if ints:
                fm[key] = ints
            if exts:
                external_refs.setdefault(key, []).extend(exts)
    if story.get("superseded_by"):
        sb = map_id(story["superseded_by"])
        if sb in in_scope:
            fm["superseded_by"] = sb
        else:
            external_refs.setdefault("superseded_by", []).append(sb)
    if story.get("also_under"):
        ints, exts = _split_internal_external(map_id_list(story["also_under"]), in_scope)
        if ints:
            fm["also_under"] = ints
        if exts:
            external_refs.setdefault("also_under", []).extend(exts)
    if story.get("audiences"):
        fm["audiences"] = list(story["audiences"])
    if story.get("external"):
        fm["external"] = story["external"]
    return fm


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------

@dataclass
class Source:
    epics: Dict[str, Dict[str, Any]]
    features: Dict[str, Dict[str, Any]]
    stories_by_feature: Dict[str, List[Dict[str, Any]]]


def load_source() -> Source:
    raw = yaml.safe_load(LEGACY_PATH.read_text(encoding="utf-8"))
    epics = {e["id"]: e for e in raw.get("epics") or []}
    features = {f["id"]: f for f in raw.get("features") or []}
    stories_by_feature: Dict[str, List[Dict[str, Any]]] = {}
    for s in raw.get("stories") or []:
        stories_by_feature.setdefault(s["feature"], []).append(s)
    return Source(epics=epics, features=features, stories_by_feature=stories_by_feature)


# ---------------------------------------------------------------------------
# Migrate one epic
# ---------------------------------------------------------------------------

def _epic_scope_ids(old_epic_id: str, src: Source) -> set:
    """Return the set of new gw_* ids that will exist after migrating this epic.
    Used to decide which depends_on/related/etc. references stay in frontmatter
    and which get exiled to body Notes (cross-epic refs that will be reconnected
    in pass 2)."""
    in_scope: set = {map_id(old_epic_id)}
    epic = src.epics[old_epic_id]
    # Always include the seed policies + glossary (written by _seed_policies.py)
    in_scope.update(f"gw_policy_{i:05d}" for i in range(1, 6))
    in_scope.update(f"gw_glossary_{i:05d}" for i in range(1, 6))
    for old_feat_id in epic.get("features") or []:
        in_scope.add(map_id(old_feat_id))
        for s in src.stories_by_feature.get(old_feat_id) or []:
            in_scope.add(map_id(s["id"]))
    return in_scope


def migrate_epic(old_epic_id: str, src: Source, dry_run: bool = False) -> Tuple[List[Path], List[str]]:
    epic = src.epics.get(old_epic_id)
    if epic is None:
        raise SystemExit(f"epic {old_epic_id} not found in source YAML")
    written: List[Path] = []
    notes: List[str] = []  # migration manual-review notes
    in_scope = _epic_scope_ids(old_epic_id, src)

    epic_id_new = map_id(old_epic_id)
    epic_slug = slugify(epic["title"])
    epic_dir = REQ_ROOT / f"{epic_id_new}_{epic_slug}"

    epic_fm = epic_frontmatter(epic)
    epic_body = build_epic_body(epic)
    epic_path = epic_dir / "EPIC.md"
    if not dry_run:
        write_node(epic_path, epic_fm, epic_body)
    written.append(epic_path)

    for old_feat_id in epic.get("features") or []:
        feature = src.features.get(old_feat_id)
        if feature is None:
            notes.append(f"{old_epic_id}: feature {old_feat_id} listed but not defined in YAML — skipped")
            continue
        feat_id_new = map_id(old_feat_id)
        feat_slug = slugify(feature["title"])
        feat_dir = epic_dir / f"{feat_id_new}_{feat_slug}"
        dropped: List[str] = []
        feat_external: Dict[str, List[str]] = {}
        feat_fm = feature_frontmatter(feature, dropped, in_scope, feat_external)
        feat_body = build_feature_body(feature, feat_external, dropped)
        if dropped:
            notes.append(f"{old_feat_id}: dropped self-edge in depends_on")
        if feat_external:
            notes.append(
                f"{old_feat_id}: deferred external refs to body Notes "
                f"({sum(len(v) for v in feat_external.values())} total)"
            )
        feat_path = feat_dir / "FEATURE.md"
        if not dry_run:
            write_node(feat_path, feat_fm, feat_body)
        written.append(feat_path)

        for story in src.stories_by_feature.get(old_feat_id) or []:
            story_id_new = map_id(story["id"])
            story_slug = slugify(story["title"])
            story_dir = feat_dir / f"{story_id_new}_{story_slug}"
            sdrop: List[str] = []
            sext: Dict[str, List[str]] = {}
            sfm = story_frontmatter(story, sdrop, in_scope, sext)
            sbody = build_story_body(story, sdrop, sext)
            if sdrop:
                notes.append(f"{story['id']}: dropped self-edge in depends_on")
            if sext:
                notes.append(
                    f"{story['id']}: deferred external refs to body Notes "
                    f"({sum(len(v) for v in sext.values())} total)"
                )
            spath = story_dir / "STORY.md"
            if not dry_run:
                write_node(spath, sfm, sbody)
            written.append(spath)
    return written, notes


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("epic", nargs="?", help="epic id (e.g. EPIC-008)")
    p.add_argument("--all", action="store_true", help="migrate every epic")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    src = load_source()
    targets: List[str]
    if args.all:
        targets = list(src.epics.keys())
    elif args.epic:
        targets = [args.epic]
    else:
        p.error("supply EPIC-NNN or --all")
        return 2
    all_notes: List[str] = []
    total = 0
    for tid in targets:
        written, notes = migrate_epic(tid, src, dry_run=args.dry_run)
        total += len(written)
        all_notes.extend(notes)
        action = "would write" if args.dry_run else "wrote"
        print(f"{tid}: {action} {len(written)} files")
    if all_notes:
        print("\nManual-review notes:")
        for n in all_notes:
            print(f"  - {n}")
    print(f"\ntotal files: {total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
